@startuml
abstract class Provider {
    - <<readonly>> imageGenerator : IImageGenerator
    + {abstract} ProviderName : string <<get>>
    + <<virtual>> LeftAmount : decimal <<get>>
    + <<virtual>> Collection : BigInteger <<get>>
    + <<virtual>> Token : Erc20Token <<get>>
    + PoolInfo : BasePoolInfo <<get>>
    + {abstract} Description : string <<get>>
    + {abstract} Urlify : BaseUrlifyModel <<get>>
    + <<virtual>> Attributes : IEnumerable<Erc721Attribute> <<get>>
    # Provider(basePoolInfo:BasePoolInfo[])
    + GetJsonErc721Metadata() : string
    - GetErc721Metadata() : Erc721Metadata
    - GetDescription() : string
    - IsFullyWithdrawn(nftAddress:string) : bool
    - IsFullyRefunded(nftAddress:string) : bool
}
@enduml
