@startuml
class DisplayAttribute {
    + DisplayName : string? <<get>>
    + DisplayAttribute(displayType:DisplayType, displayName:string?)
    + TryGetErc721Attribute(propertyName:string, value:object?, erc721Attribute:Erc721Attribute) : bool
}
Attribute <|-- DisplayAttribute
DisplayAttribute --> "DisplayType" DisplayType
@enduml
