@startuml
class ImageGenerator {
    + ImageGenerator()
    + ImageGenerator(renderer:IImageRenderer, shortener:IUrlShortener)
    + Generate(urlify:BaseUrlifyModel, description:string) : string
}
IImageGenerator <|-- ImageGenerator
ImageGenerator --> "renderer" IImageRenderer
ImageGenerator --> "shortener" IUrlShortener
@enduml
