@startuml
class DealProvider {
    + <<override>> ToString() : string
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> Urlify : BaseUrlifyModel <<get>>
    + DealProvider(basePoolInfos:BasePoolInfo[])
    + DealProvider(basePoolInfo:BasePoolInfo)
}
Provider <|-- DealProvider
@enduml
