@startuml
class LockDealProvider {
    + <<override>> ToString() : string
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + StartTime : uint <<get>>
    + StartDateTime : DateTime <<get>>
    + <<override>> Urlify : BaseUrlifyModel <<get>>
    + LockDealProvider(basePoolInfo:BasePoolInfo[])
}
DealProvider <|-- LockDealProvider
@enduml
