@startuml
class LockDealProvider {
    + <<override>> ToString() : string
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + StartTime : uint <<get>>
    + LockDealProvider(basePoolInfo:BasePoolInfo[])
}
DealProvider <|-- LockDealProvider
LockDealProvider --> "StartDateTime" DateTime
LockDealProvider --> "Urlify" BaseUrlifyModel
@enduml
