@startuml
class TimedDealProvider {
    + <<override>> ToString() : string
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + StartAmount : decimal <<get>>
    + FinishTime : uint <<get>>
    + TimedDealProvider(basePoolInfo:BasePoolInfo[])
}
LockDealProvider <|-- TimedDealProvider
TimedDealProvider --> "FinishDateTime" DateTime
TimedDealProvider --> "Urlify" BaseUrlifyModel
@enduml
