@startuml
class CollateralProvider {
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> Urlify : BaseUrlifyModel <<get>>
    + MainCoin : Erc20Token <<get>>
    + MainCoinCollection : BigInteger <<get>>
    + <<override>> Collection : BigInteger <<get>>
    + <<override>> LeftAmount : decimal <<get>>
    + MainCoinCollectorAmount : decimal <<get>>
    + TokenCollectorAmount : decimal <<get>>
    + MainCoinHolderAmount : decimal <<get>>
    + FinishTimestamp : uint <<get>>
    <<internal>> FinishTime : DateTime <<get>>
    <<internal>> SubProvider : Dictionary<CollateralType,DealProvider> <<get>>
    + CollateralProvider(basePoolInfo:BasePoolInfo)
    + CollateralProvider(basePoolInfo:BasePoolInfo[])
}
enum CollateralType {
    MainCoinCollector= 1,
    TokenCollector= 2,
    MainCoinHolder= 3,
}
Provider <|-- CollateralProvider
CollateralProvider +-- CollateralType
@enduml
