@startuml
class RefundProvider {
    + <<override>> ProviderName : string <<get>>
    + <<override>> Description : string <<get>>
    + Rate : decimal <<get>>
    + MainCoinAmount : decimal <<get>>
    + SubProviderName : string <<get>>
    + RefundProvider(basePoolInfo:BasePoolInfo[])
}
Provider <|-- RefundProvider
RefundProvider --> "Urlify" BaseUrlifyModel
RefundProvider --> "SubProvider" Provider
RefundProvider --> "CollateralProvider" CollateralProvider
RefundProvider --> "MainCoinCollection" BigInteger
@enduml
