@startuml
class Erc721Attribute {
    + DisplayType : DisplayType <<get>>
    + TraitType : string <<get>>
    + Value : object <<get>>
    + Erc721Attribute(traitType:string, value:object, displayType:DisplayType)
}
@enduml
