@startuml
class Erc721Metadata {
    + Name : string <<get>>
    + Description : string <<get>>
    + Image : string <<get>>
    + Erc721Metadata(name:string, description:string, image:string, attributes:IEnumerable<Erc721Attribute>)
}
class "IEnumerable`1"<T> {
}
Erc721Metadata --> "Attributes<Erc721Attribute>" "IEnumerable`1"
@enduml
