@startuml
class LambdaFunction {
    - <<readonly>> providerFactory : ProviderFactory
    + LambdaFunction()
    + LambdaFunction(providerFactory:ProviderFactory)
    + FunctionHandler(request:LambdaRequest) : APIGatewayProxyResponse
}
@enduml
