name: .NET Core Test Coverage

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests and collect coverage
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/

    - name: Install ReportGenerator tool
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: reportgenerator -reports:${{ github.workspace }}/TestResults/Coverage/*.cobertura.xml -targetdir:${{ github.workspace }}/TestResults/Coverage/Reports -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Upload coverage to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./TestResults/Coverage/Reports/
