name: Build with Markdown Report

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PACKAGE_USER_NAME: ${{ github.actor }}
  GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build-and-test:
        uses: The-Poolz/.net-workflows/.github/workflows/coverage-report.yml@master
