name: Build with Markdown Report

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build-and-test:
        uses: The-Poolz/.net-workflows/.github/workflows/coverage-report.yml@master
